class User_Profile_Locators:

    EDIT_PROFILE_BUTTON = 'button[class="edit-user-btn"]'
    VALIDATION_FOR_EDIT_BUTTON = 'div[class="user-update-wrapper"]'
    NAME_INPUT = 'input[name="name"]'
    LAST_NAME_INPUT = 'input[name="lastName"]'
    EMAIL_INPUT = 'input[name="email"]'
    BIRTH_DATE_INPUT = 'input[name="birthDate"]'
    IMAGE_INPUT = 'input[name="image"]'
    LOG_OUT_BUTTON = 'button[class="logout-btn"]'
    VALIDATION_FOR_LOG_BUTTON = 'section[class="sc-pVTFL jQTpoc"]'
    UPDATE_BUTTON = '//form/button'
    FULL_NAME = '//div[2]/h2[1]'
    AGE = '//div[2]/h2[2]'

    CITY_OPTION = '//ul/li[1]/a'
    HOTELS_OPTION = '//ul/li[2]/a'
    RESTAURANTS_OPTION = '//ul/li[3]/a'
    ACTIVITIES_OPTION = '//ul/li[4]/a'
    VALIDATION_FOR_NAVBAR_LIST_OPTION = 'h1[class="category-name-h1"]'
    VALIDATION_FOR_CITY_OPTION = 'h1[class="city-name-h1"]'

    SELECT_BOX = '//select'
    SORT_BUTTON = 'button[class="sort-btn"]'
    RESTAURANTS_SLIDER = '//section[1]/div[1]/div[1]'
    HOTELS_SLIDER = '//section[1]/div[2]/div[1]'
    ACTIVITIES_SLIDER = ' //section[1]/div[3]/div[1]'